inherit_from: .rubocop_todo.yml

# .rubocop.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/OneClassPerFile:
  Exclude:
    - 'examples/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
